version: '3.7'

services:
  frontal:
    container_name: frontal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING="true"
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
